language: rust
rust:
    - stable
cache:
  cargo: true
  timeout: 1200
addons:
  apt:
    packages:
      - unzip
before_install:
  - rustup component add rustfmt-preview clippy-preview
env:
  global:
    - RUST_BACKTRACE=1
    # Enables additional cpu-specific optimizations.
    - RUSTFLAGS="-D warnings -C target-cpu=native"
script:
  - cargo clippy --tests --examples --benches -- --deny clippy
  - cargo clippy --all-features --tests --examples --benches -- --deny clippy
  - cargo fmt -- --check
  - cargo test --all-features --release
