language: rust
rust:
    - 1.29.1
cache:
  cargo: true
  timeout: 1200
addons:
  apt:
    packages:
      - unzip
before_install:
  - rustup component add --toolchain=${TRAVIS_RUST_VERSION} rustfmt-preview clippy-preview
  - cargo deadlinks --version || cargo install cargo-deadlinks
env:
  global:
    - RUST_BACKTRACE=1
    # Enables additional cpu-specific optimizations.
    - RUSTFLAGS="-D warnings -C target-cpu=native"
script:
  - cargo clippy --tests --examples --benches -- --deny clippy
  - cargo fmt -- --check
  - cargo test --release
  - cargo test --all-features --release
  - cargo doc
  - cargo deadlinks --dir target/doc/threshold_crypto/
